package videoteca;

public enum Genere {
    COMMEDIA, AZIONE, FANTASCIENZA, ANIMAZIONE, DRAMMATICO, HORROR, THRILLER, ROMANTICO, DOCUMENTARIO, MUSICALE, FANTASY, WESTERN, STORICO, AVVENTURA, MISTERY, CRIMINALE, SPORTIVO;
}
